# Generated by Django 4.2.2 on 2023-06-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_start',
            field=models.DateField(default=None),
        ),
    ]
