# Generated by Django 4.2.2 on 2023-06-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_booking_trip_end_booking_trip_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip_end',
            field=models.DateField(default=True),
        ),
    ]
